feat: button component
adith-a-danthi/tidle-ui pull request #3
Opened 2022-02-07 15:27 UTC by adith-a-danthi

Added Button Component
- Standard Buttons
- Outlined Buttons
- Floating Action Button
- Link Button
- Button Sizes `default` `small`, `large`

![image](https://user-images.githubusercontent.com/39412016/152817708-12bf505c-4a42-4a89-915f-3bb946b05a38.png)

2022-02-07 16:32 UTC, dikshadhote requested changes
Code is neat and clean. just take care of naming conventions and unit values.

2022-02-07 16:32 UTC, dikshadhote commented on docs/components/buttons/buttons.html
> +        <section id="fab">
use proper naming convection instead of fab for eg .floating-btn

2022-02-07 16:32 UTC, dikshadhote commented on docs/components/buttons/buttons.css
> +  padding: 0.35rem 0.75rem;
use px for values less than 10 or 12 px

2022-02-09 15:10 UTC, mnath30 commented on docs/components/buttons/buttons.css
> +  color: white;
You can use variables here as well for the color

2022-02-09 15:12 UTC, mnath30 approved these changes
Code looks clean and good use of comments. Great work.

2022-02-09 15:54 UTC, merged